[book]
authors = ["Jason"]
language = "zh-cn"
multilingual = false
src = "src"
title = "[智化空知识库-hao.aihg.top](https://hao.aihg.top)"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-js = ["assets/fzf.umd.js", "assets/elasticlunr.js", "assets/mermaid.min.js", "assets/mermaid-init.js"]
input-404 = "404.md"
site-url = "https://hao.aihg.top/chemtour/"

[preprocessor.katex]
after = ["links"]
